/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/

export function StartPulse() {
  Tags("HMI_Start_PB").Write(
    true,
    HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
  );

  HMIRuntime.Timers.SetTimeout(function ResetStartPulse() {
    Tags("HMI_Start_PB").Write(
      false,
      HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
    );
  }, 200);
}

export function StopPulse() {
  Tags("HMI_Stop_PB").Write(
    true,
    HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
  );

  HMIRuntime.Timers.SetTimeout(function ResetStopPulse() {
    Tags("HMI_Stop_PB").Write(
      false,
      HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
    );
  }, 200);
}

export function WriteSetValue(value) {
  Tags("HMI_SetValue").Write(
    Number(value),
    HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
  );
}

export function StartWithPreset(value) {
  let ts = Tags.CreateTagSet([
    ["HMI_SetValue", Number(value)],
    ["HMI_Start_PB", true]
  ]);

  ts.Write(HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait);

  HMIRuntime.Timers.SetTimeout(function ResetStartPulse() {
    Tags("HMI_Start_PB").Write(
      false,
      HMIRuntime.Tags.Enums.hmiWriteType.hmiWriteWait
    );
  }, 200);
}

export function ReadClosedLoopState() {
  let ts = Tags.CreateTagSet([
    "HMI_Run_Cmd",
    "HMI_Lamp_FB",
    "HMI_SetValue",
    "HMI_ActualValue"
  ]);

  ts.Read(HMIRuntime.Tags.Enums.hmiReadType.hmiReadDirect);

  HMIRuntime.Trace(
    "Run=" + ts("HMI_Run_Cmd").Value +
    ", Lamp=" + ts("HMI_Lamp_FB").Value +
    ", Set=" + ts("HMI_SetValue").Value +
    ", Actual=" + ts("HMI_ActualValue").Value
  );

  return ts;
}
